main:
    path: /
    defaults: {_controller: MainBundle:Menu:index }
    
register:
    path: /registerz
    defaults: {_controller: MainBundle:Menu:register }
    
view:
    path: /view
    defaults: {_controller: MainBundle:Admin:userview} 
    
details:
    path: /details/{id}
    defaults: {_controller: MainBundle:Admin:details} 
    
new_advert:
    path: /new_advert
    defaults: {_controller: MainBundle:Menu:addAdvert }

adverts:
    path: /adverts
    defaults: {_controller: MainBundle:Menu:adverts }

advert:
    path: /advert/{id}
    defaults: {_controller: MainBundle:Advert:advertDetails }   

search:
    path: /search
    defaults: {_controller: MainBundle:Advert:search }
        
