main:
    path: /
    defaults: {_controller: MainBundle:Menu:index }
    
register:
    path: /register
    defaults: {_controller: MainBundle:Menu:register }
    
about:
    path: /view
    defaults: {_controller: MainBundle:Admin:userview} 
    
details:
    path: /details/{id}
    defaults: {_controller: MainBundle:Admin:details} 
    
