parameters:
    main.service.advert.class: MainBundle\Resources\views\advertService
    
services:
    main_adverts:
        class: %main.service.advert.class%
        arguments: [@doctrine.orm.entity_manager]