services:
    app.twig_extension:
        class: MainBundle\Service\advertService
        arguments: 
             - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }
        